"""
Linear interpolation path planner for drone navigation.

Generates waypoints from start to goal using simple linear interpolation.
Fast, deterministic, and 100% reliable - obstacles handled by reactive avoidance.
"""

import math
from typing import List, Tuple


def generate_waypoints_linear(start_x: float, start_y: float,
                               goal_x: float, goal_y: float,
                               altitude: float,
                               num_intermediate: int = 3) -> List[Tuple[float, float, float]]:
    """
    Generate waypoints using linear interpolation.

    This is a simple, fast, and deterministic algorithm that creates waypoints
    along a straight line from start to goal. Obstacle avoidance is handled
    by the reactive navigation system during flight.

    Algorithm:
    1. Create start waypoint at (start_x, start_y, altitude)
    2. Generate N intermediate waypoints evenly spaced along line
    3. Create goal waypoint at (goal_x, goal_y, altitude)
    4. Add landing waypoint at (goal_x, goal_y, 0)

    Math:
        For waypoint i (where i = 1 to num_intermediate):
            ratio = i / (num_intermediate + 1)
            wp_x = start_x + (goal_x - start_x) * ratio
            wp_y = start_y + (goal_y - start_y) * ratio
            wp_z = altitude (constant)

    Benefits:
    - 100% success rate (always generates valid path)
    - O(1) time complexity - instant (< 1ms)
    - Deterministic - same inputs always produce same waypoints
    - Energy efficient - straight line is shortest path
    - Simple to understand and debug
    - Works perfectly with reactive obstacle avoidance

    Limitations:
    - Does not pre-plan around obstacles (relies on reactive avoidance)
    - Assumes obstacles can be dodged in real-time

    Args:
        start_x, start_y: Start position in cm
        goal_x, goal_y: Goal position in cm
        altitude: Flight altitude in cm
        num_intermediate: Number of intermediate waypoints (default 3)

    Returns:
        List of waypoints [(x, y, z), ...] including takeoff, intermediate points, goal, and landing

    Example:
        >>> waypoints = generate_waypoints_linear(0, 0, 300, 200, 120, num_intermediate=3)
        >>> # Returns: [(0, 0, 120), (75, 50, 120), (150, 100, 120), (225, 150, 120),
        >>>              (300, 200, 120), (300, 200, 0)]
    """
    waypoints = []

    # Calculate distance for logging
    distance = math.sqrt((goal_x - start_x)**2 + (goal_y - start_y)**2)
    print(f"[Linear Planner] Planning path from ({start_x}, {start_y}) to ({goal_x}, {goal_y})")
    print(f"[Linear Planner] Distance: {distance:.1f}cm, Altitude: {altitude}cm")
    print(f"[Linear Planner] Generating {num_intermediate + 2} waypoints (plus landing)")

    # 1. Start waypoint (takeoff position)
    waypoints.append((start_x, start_y, altitude))

    # 2. Intermediate waypoints via linear interpolation
    for i in range(1, num_intermediate + 1):
        ratio = i / (num_intermediate + 1)
        wp_x = start_x + (goal_x - start_x) * ratio
        wp_y = start_y + (goal_y - start_y) * ratio
        waypoints.append((wp_x, wp_y, altitude))

    # 3. Goal waypoint
    waypoints.append((goal_x, goal_y, altitude))

    # 4. Landing waypoint
    waypoints.append((goal_x, goal_y, 0))

    print(f"[Linear Planner] Generated {len(waypoints)} waypoints:")
    for idx, (x, y, z) in enumerate(waypoints):
        print(f"  WP{idx + 1}: ({x:.1f}, {y:.1f}, {z:.1f})cm")

    return waypoints


# Legacy alias for backward compatibility
def generate_waypoints_with_rrt(start_x: float, start_y: float,
                                 goal_x: float, goal_y: float,
                                 altitude: float,
                                 obstacles: List[Tuple[float, float, float]] = None) -> List[Tuple[float, float, float]]:
    """
    Legacy function name - now uses linear interpolation instead of RRT.

    This function maintains the same interface but uses the simpler linear
    interpolation algorithm. The obstacles parameter is ignored since
    obstacle avoidance is handled reactively during flight.

    Args:
        start_x, start_y: Start position in cm
        goal_x, goal_y: Goal position in cm
        altitude: Flight altitude in cm
        obstacles: Ignored (maintained for compatibility)

    Returns:
        List of waypoints generated by linear interpolation
    """
    return generate_waypoints_linear(start_x, start_y, goal_x, goal_y, altitude)
